Repository Tech-Phantoms/.github, pull requests merged in 2021-11, with the labels that each got.

#17 docs: Text improvements for the readme profile
  profile/README.md
Labels: type: docs

#19 Add contact information in the issue template configuration
  .github/ISSUE_TEMPLATE/config.yml
Labels: type: feature

#21 UPDATE Org Readme
  profile/README.md
Labels: status: approved

#22 feat: Update the readme profile
  profile/README.md
Labels: type: docs

#23 feat: Add Instagram and logo badges
  profile/README.md
Labels: type: feature
